@Restaurants.API_HostAddress = https://localhost:7203
@Token = CfDJ8HP9Jeg4IllClSoVbawfrq28XXQvM8hqCnNDnzmQab-gbMqvO39tZt-o-oqFoxg2sa13ZwvZbrN5iFzPAv5qnQBzA9rEgeYJ7wxbmR9qmq0YaxoukgZT98bHjjZyxdg5x-rHon9gpgIMyOOF9NgW0rT786iaaxXkGRtgkBOzBL82TRnsxoUnazytRuQa1cvqPxp1JdlN6i7Jmafe9EhjPXafEBH9qt05MPx3PubklV3FNJ7hZI-oCQPrS60V0dYIoU0KacMPSgpz2pBhSvNuMzKM8pV2neJvnvemS3x4a52j1Ge_OhqkVCUUIzEAJ8UAX-D8bnrREX9ke5dOc-ij6Wsneg2Vi3TZiImNEGtAHhhZzeiLwX-It5lzaWwWxRlhMRZXgAiYw5xCvl3pXR6cIxStsd1TeoR9tAdO5B_Un1H9qq9QG29MobKjoQBRHl7Sv2gNu20M5tY_UPtbkEDYdadC9_fvIR2rsmuR3z9rC3UQWEc4sPIXdz65_hiZEOpXabgbgosi1m01DqhRVbgLB2QePGnJSvP2Uh47d4_YbVt3QcF_2-hm02NJDXgjsHe0bouSFScKhlbSRqOsL2gQoJ8JESjYj6Nreze2o_ZsVUtTff63bjdtLEm7aQtlAJs9QNYrtY2lPFm3QBfreZV9k4yyzWCiK1bkWecObYGtiE4XlVSvXLsdw7yzDcnHQULOytvpfbpoVQltfIKF6SVQBN7q-1901NjbQK2HS3HE9sssUfpm5hRKrUwADCz-umJXz6N4M5h7jrG-ZHW7KVY_p394aBFKYUlm60d1WxyTj0djVYvZ-aTUIFWO_vNkjt2T1ZRkJwpCHCosEKOQ55li7gMcNODgM_Rhrk73v94rfFh-Sg34mg6Q-uXKDSQgG_Xf4A
GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{Token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###


GET https://localhost:7203/api/restaurants/6

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/8

###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json; charset=utf-8

{
  "Name": "Test123",
  "Description": "Test dishes123",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "Name": "Spaghetti",
  "Description": "Italian Restaurant",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "spaghetti@gmai.com",
  "ContactNumber": "345-1234",
  "City": "Rome",
  "Street": "Main Street",
  "PostalCode": "10-010"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes
Authorization: Bearer {{Token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password123!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password123!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  {
  "userEmail": "admin@test.com",
  "roleName": "Admin"
}
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "Nationality": "Italian",
  "DateOfBirth": "2010-01-01"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/identity/deleteRole
Authorization: Bearer {{Token}}

{
  "userEmail": "Toklika@gmail.com",
  "roleName": "User"
}
###
