@Restaurants.API_HostAddress = https://localhost:7203
@Token = CfDJ8HP9Jeg4IllClSoVbawfrq0Y-wal8TvQrBHvE7wFluXGL-nMfNmSAiHwwW4o-Pw7Z5dM7zC-sIxxcVj2VdJ058LpXxG04x1t9gXULp5wp73MZeY03dfPkqL9r2LHMITCRxxuOw3dvoogLxTvd0PotfBWpsioBjJvauU_mJyfv0O3rYmEA4sGktytT2bJgjMfn4hYMxBor1eODJj-9ajzIXhJpHPP7j0UKBysWO-wIZdH4iEmWX0h4uy0zct1Vi7_UStXDhq87cVH2XqZtWCfLx1Yb3vMVYHmHSkV6fA7m-HFhZni4HTn4Wl7hw0SxsL8BodHIENEOuhfb_N2Y9iS05uh7Ju_aOKxwT8BV4_A_zePvmPnerFsnWHR7T05kOOIIUhCgtA9-J3WotHcEcjpy-j2zI6u7rdCrXWBCNI2p_AaIQtzswGgO-jpe-zlk3b9BM19Su1dEm-gSK3ZzQIJT1HXLG2CAcCLSDdc2x91RvK4Gygvi0fCuQ85q3bAhXTt6atPcYlFStDaQtMyDQJUq3DhO1KN2Uk8Ly9x3l-Jas5WD47Szy7RMcBo_LQDBbKY6JXgFJ-iS_1YKufx3f0gCEGRcKNWUlbvAzIya-Fcj9xrDVIM_MSiT2yrFSVmfVSZKz_ZgXUmIGCjJuV154sZIvnUB1eNxcbpzifqMf9bkGTuYGcovlEQPNTS93tHHcH6VP-1ud6ayDpdm02WAiYUpKxtHGKG-65jNEbAGG2AOsbHRVCkolhzETRxFUanZ2kmuzRByGEbBIyHjxqTUyByGMw
GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{Token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###


GET https://localhost:7203/api/restaurants/6

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/8

###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json; charset=utf-8

{
  "Name": "Test123",
  "Description": "Test dishes123",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "Name": "Spaghetti boloneze",
  "Description": "Italian pasta with cheese",
  "Price": 23.70,
  "KiloCalories": 750,
  "Category": "Georgian"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes
Authorization: Bearer {{Token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password123!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "Toklika@gmail.com",
  "password": "Password123!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  {
  "userEmail": "admin@test.com",
  "roleName": "Admin"
}
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "Nationality": "Italian",
  "DateOfBirth": "2010-01-01"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/identity/deleteRole
Authorization: Bearer {{Token}}

{
  "userEmail": "Toklika@gmail.com",
  "roleName": "User"
}
###
